name = "cheapship-api"
compatibility_date = "2024-01-01"
main = "src/workers/index.js"

# Configuration D1 Database
[[d1_databases]]
binding = "CHEAPSHIP_DB"
database_name = "cheapship-production"
database_id = "2741465a-22c8-4178-b37d-d9a8b410a864"

# Variables d'environnement pour production
[env.production.vars]
NODE_ENV = "production"
JWT_SECRET = "votre-secret-jwt-super-securise-ici"
FRONTEND_URL = "https://cheapship.pages.dev"

# Variables pour développement local
[env.development.vars]
NODE_ENV = "development"
JWT_SECRET = "dev-secret-cheapship-2024"
FRONTEND_URL = "http://localhost:5173"

# Compatibilité
compatibility_flags = ["nodejs_compat"]